issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:DevExpPlatform/(project-gcio-[^:]+|project-workforce-management-backend):.*'

permissions:
  contents: write
  pull_requests: write
  metadata: read

repositories: []
