issuer: https://token.actions.githubusercontent.com
subject_pattern: 'repo:DevExpPlatform/project-gcio(?:-[^:]+)?:.*'

permissions:
  contents: write
  pull_requests: write
  metadata: read
  packages: read

repositories: []
