issuer: https://token.actions.githubusercontent.com
subject_pattern: .*

permissions:
  contents: read
  issues: read
  organization_projects: read
  pull_requests: write

repositories: [] # Act over all of the repos in the org.